// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace KurumsalFramework.Northwind.DataAccess.Concreate.EntityFramework.Mappings
{
    using KurumsalFramework.Core.Entities;
    using KurumsalFramework.Northwind.Entities.Concreate;

    // CustomerDemographics
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class CustomerDemographicMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CustomerDemographic>
    {
        public CustomerDemographicMapping()
            : this("dbo")
        {
        }

        public CustomerDemographicMapping(string schema)
        {
            ToTable("CustomerDemographics", schema);
            HasKey(x => x.CustomerTypeId);

            Property(x => x.CustomerTypeId).HasColumnName(@"CustomerTypeID").HasColumnType("nchar").IsRequired().IsFixedLength().HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CustomerDesc).HasColumnName(@"CustomerDesc").HasColumnType("ntext").IsOptional().IsMaxLength();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
