// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace KurumsalFramework.Northwind.DataAccess.Concreate.EntityFramework
{
    using KurumsalFramework.Core.Entities;
    using KurumsalFramework.Northwind.DataAccess.Concreate.EntityFramework.Mappings;
    using KurumsalFramework.Northwind.Entities.Concreate;

    public partial class NorthwindDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<NorthwindDbContext>
    {
        public NorthwindDbContext Create()
        {
            return new NorthwindDbContext();
        }
    }
}
// </auto-generated>
