// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace KurumsalFramework.Northwind.Entities.Concreate
{
    using KurumsalFramework.Core.Entities;

    // Customers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Customer : IEntity
    {
         public virtual string CustomerId { get; set; } // CustomerID (Primary key) (length: 5)
         public virtual string CompanyName { get; set; } // CompanyName (length: 40)
         public virtual string ContactName { get; set; } // ContactName (length: 30)
         public virtual string ContactTitle { get; set; } // ContactTitle (length: 30)
         public virtual string Address { get; set; } // Address (length: 60)
         public virtual string City { get; set; } // City (length: 15)
         public virtual string Region { get; set; } // Region (length: 15)
         public virtual string PostalCode { get; set; } // PostalCode (length: 10)
         public virtual string Country { get; set; } // Country (length: 15)
         public virtual string Phone { get; set; } // Phone (length: 24)
         public virtual string Fax { get; set; } // Fax (length: 24)

        // Reverse navigation

        /// <summary>
        /// Child CustomerDemographics (Many-to-Many) mapped by table [CustomerCustomerDemo]
        /// </summary>
        public virtual System.Collections.Generic.IList<CustomerDemographic> CustomerDemographics { get; set; } // Many to many mapping
        /// <summary>
        /// Child Orders where [Orders].[CustomerID] point to this entity (FK_Orders_Customers)
        /// </summary>
        public virtual System.Collections.Generic.IList<Order> Orders { get; set; } // Orders.FK_Orders_Customers

        public Customer()
        {
            Orders = new System.Collections.Generic.List<Order>();
            CustomerDemographics = new System.Collections.Generic.List<CustomerDemographic>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
