// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace KurumsalFramework.Northwind.Entities.Concreate
{
    using KurumsalFramework.Core.Entities;

    // Employees
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Employee : IEntity
    {
         public virtual int EmployeeId { get; set; } // EmployeeID (Primary key)
         public virtual string LastName { get; set; } // LastName (length: 20)
         public virtual string FirstName { get; set; } // FirstName (length: 10)
         public virtual string Title { get; set; } // Title (length: 30)
         public virtual string TitleOfCourtesy { get; set; } // TitleOfCourtesy (length: 25)
         public virtual System.DateTime? BirthDate { get; set; } // BirthDate
         public virtual System.DateTime? HireDate { get; set; } // HireDate
         public virtual string Address { get; set; } // Address (length: 60)
         public virtual string City { get; set; } // City (length: 15)
         public virtual string Region { get; set; } // Region (length: 15)
         public virtual string PostalCode { get; set; } // PostalCode (length: 10)
         public virtual string Country { get; set; } // Country (length: 15)
         public virtual string HomePhone { get; set; } // HomePhone (length: 24)
         public virtual string Extension { get; set; } // Extension (length: 4)
         public virtual byte[] Photo { get; set; } // Photo (length: 2147483647)
         public virtual string Notes { get; set; } // Notes (length: 1073741823)
         public virtual int? ReportsTo { get; set; } // ReportsTo
         public virtual string PhotoPath { get; set; } // PhotoPath (length: 255)

        // Reverse navigation

        /// <summary>
        /// Child Employees where [Employees].[ReportsTo] point to this entity (FK_Employees_Employees)
        /// </summary>
        public virtual System.Collections.Generic.IList<Employee> Employees { get; set; } // Employees.FK_Employees_Employees
        /// <summary>
        /// Child Orders where [Orders].[EmployeeID] point to this entity (FK_Orders_Employees)
        /// </summary>
        public virtual System.Collections.Generic.IList<Order> Orders { get; set; } // Orders.FK_Orders_Employees
        /// <summary>
        /// Child Territories (Many-to-Many) mapped by table [EmployeeTerritories]
        /// </summary>
        public virtual System.Collections.Generic.IList<Territory> Territories { get; set; } // Many to many mapping

        // Foreign keys

        /// <summary>
        /// Parent Employee pointed by [Employees].([ReportsTo]) (FK_Employees_Employees)
        /// </summary>
        public virtual Employee Employee_ReportsTo { get; set; } // FK_Employees_Employees

        public Employee()
        {
            Employees = new System.Collections.Generic.List<Employee>();
            Orders = new System.Collections.Generic.List<Order>();
            Territories = new System.Collections.Generic.List<Territory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
