// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace KurumsalFramework.Northwind.Entities.Concreate
{
    using KurumsalFramework.Core.Entities;

    // Orders
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Order : IEntity
    {
         public virtual int OrderId { get; set; } // OrderID (Primary key)
         public virtual string CustomerId { get; set; } // CustomerID (length: 5)
         public virtual int? EmployeeId { get; set; } // EmployeeID
         public virtual System.DateTime? OrderDate { get; set; } // OrderDate
         public virtual System.DateTime? RequiredDate { get; set; } // RequiredDate
         public virtual System.DateTime? ShippedDate { get; set; } // ShippedDate
         public virtual int? ShipVia { get; set; } // ShipVia
         public virtual decimal? Freight { get; set; } // Freight
         public virtual string ShipName { get; set; } // ShipName (length: 40)
         public virtual string ShipAddress { get; set; } // ShipAddress (length: 60)
         public virtual string ShipCity { get; set; } // ShipCity (length: 15)
         public virtual string ShipRegion { get; set; } // ShipRegion (length: 15)
         public virtual string ShipPostalCode { get; set; } // ShipPostalCode (length: 10)
         public virtual string ShipCountry { get; set; } // ShipCountry (length: 15)

        // Reverse navigation

        /// <summary>
        /// Child OrderDetails where [Order Details].[OrderID] point to this entity (FK_Order_Details_Orders)
        /// </summary>
        public virtual System.Collections.Generic.IList<OrderDetail> OrderDetails { get; set; } // Order Details.FK_Order_Details_Orders

        // Foreign keys

        /// <summary>
        /// Parent Customer pointed by [Orders].([CustomerId]) (FK_Orders_Customers)
        /// </summary>
        public virtual Customer Customer { get; set; } // FK_Orders_Customers

        /// <summary>
        /// Parent Employee pointed by [Orders].([EmployeeId]) (FK_Orders_Employees)
        /// </summary>
        public virtual Employee Employee { get; set; } // FK_Orders_Employees

        /// <summary>
        /// Parent Shipper pointed by [Orders].([ShipVia]) (FK_Orders_Shippers)
        /// </summary>
        public virtual Shipper Shipper { get; set; } // FK_Orders_Shippers

        public Order()
        {
            Freight = 0m;
            OrderDetails = new System.Collections.Generic.List<OrderDetail>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
