// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace KurumsalFramework.Northwind.Entities.Concreate
{
    using KurumsalFramework.Core.Entities;

    // Region
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public partial class Region : IEntity
    {
         public virtual int RegionId { get; set; } // RegionID (Primary key)
         public virtual string RegionDescription { get; set; } // RegionDescription (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Territories where [Territories].[RegionID] point to this entity (FK_Territories_Region)
        /// </summary>
        public virtual System.Collections.Generic.IList<Territory> Territories { get; set; } // Territories.FK_Territories_Region

        public Region()
        {
            Territories = new System.Collections.Generic.List<Territory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
